[server]
host = "0.0.0.0"
port = 8080

[database]
host = "localhost"
port = 5433
user = "otus_user"
password = ""
dbname = "otus"

[auth]
jwt_cookie_name = "token"
jwt_key = "secret_key"
jwt_expire_hours   = 24

[redis]
host = "localhost"
port = 6379
password = ""
db = 0

[citus]
coordinator = true

[[citus.node]]
host = "citus_worker1"
port = 5432

[[citus.node]]
host = "citus_worker2"
port = 5432
